version: '3'
services:
  db-mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - ./expertfy-api/src/data/db-dump:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  api-expertfy:
    build:
      context: ./expertfy-api
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db-mysql
    volumes:
      - ./expertfy-api/src:/usr/src/app/src
  fe-expertfy:
    build:
      context: ./expertfy-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - api-expertfy
    volumes:
      - ./expertfy-front:/usr/src/app/src # Descomente para utilizar o recurso de hot reload (ctrl + s = atualiza a página)

volumes:
  db-volume: