version: '3'
services:
  db-mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env.dev
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./expertfy-api/src/data/db-dump/dump_tabelas.sql:/docker-entrypoint-initdb.d/init.sql
  api-expertfy:
    build:
      context: ./expertfy-api
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db-mysql
  fe-expertfy:
    build:
      context: ./new-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - api-expertfy

volumes:
  db-volume: