version: '3'
services:
  db-mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - ./expertfy-api/src/data/new-db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  api-expertfy:
    build:
      context: ./expertfy-api
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db-mysql
  fe-expertfy:
    build:
      context: ./new-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - api-expertfy

volumes:
  db-volume: